version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    
    ports:
      - "8000:8000"

    volumes:
      - ./app:/app

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    
    env_file:
      - .env
    
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      args:
        - DEV=true

    volumes:
      - ./app:/app

    command: >
      sh -c "python manage.py celery_worker"
    
    env_file:
      - .env
    
    depends_on:
      - db
      - redis


  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"

    volumes:
      - dev-db-data:/var/lib/postgresql/data
    # environment:
    #  POSTGRES_USER: ${POSTGRES_USER}
    #  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #  POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025

  redis:
    image: redis:7.2-alpine
    

volumes:
  dev-db-data:
