version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=false
    
    ports:
      - "8000:8000"

    volumes:
      - ./app:/app

    command: >
      sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    
    env_file:
      - .env.prod
    
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      args:
        - DEV=false

    volumes:
      - ./app:/app

    command: >
      sh -c "python manage.py celery_worker"
    
    env_file:
      - .env.prod
    
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"

    volumes:
      - prod-db-data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025

  redis:
    image: redis:7.2-alpine
    

volumes:
  prod-db-data:
