version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    
    ports:
      - "8000:8000"

    volumes:
      - ./app:/app

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    
    env_file:
      - .env
    
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"

    volumes:
      - dev-db-data:/var/lib/postgresql/data
    # environment:
    #  POSTGRES_USER: ${POSTGRES_USER}
    #  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #  POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env

volumes:
  dev-db-data: