# Generated by Django 4.2.9 on 2024-01-30 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_url', models.CharField(max_length=512)),
                ('server_name', models.CharField(max_length=512)),
                ('query_string', models.TextField(null=True)),
                ('user_uuid', models.CharField(max_length=255, null=True)),
                ('check_user', models.BooleanField(default=True)),
                ('datetime_init', models.DateTimeField()),
                ('http_user_agent', models.CharField(max_length=512, null=True)),
                ('remote_address', models.GenericIPAddressField()),
                ('request_method', models.CharField(max_length=100)),
                ('response_status_code', models.PositiveSmallIntegerField(default=200)),
                ('response_time_second', models.DecimalField(decimal_places=6, max_digits=10)),
                ('datetime_end', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
